const hats = [
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/AviatorsHat/AviatorsHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/BaseballCap/BaseballCap.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/ChefHat/SM_ChefHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/ConstructionHelmet/SM_ConstructionHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/CowboyHat/CowboyHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/Crown/Crown.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/DeerstalkerCap/DeerstalkerCap.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/FirefighterHelmet/FirefighterHelmet.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/FishermansCap/FishermansCap.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/PirateHat/PirateHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/SamuraiHelmet/SamuraiHelmet.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/TopHat/SM_TopHat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/VikingHelmet/VikingHelmet.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hats/WitchesHat/WitchesHat.fbx",
];

const hands = ["https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/Balloons/Balloon.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/BaseballBat/BaseballBat.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/BowandArrow/BowandArrow.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/BoxingGloves/BoxingGlove_left.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/FishingRod/FishingRod.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/MagnifyingGlass/SM_MagnifyingGlass.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/PhotoCamera/PhotoCamera.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/RollingPin/SM_RollingPin.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/RoyalSceptre/RoyalSceptre.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/Shield/Shield.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/Spatula/Spatula.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/SwordFantasy/Sword_00.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/SwordPirate/SM_Sword-Pirate.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/TennisRacket/SM_TennisRacket.fbx",
  "https://passage.s3.us-east-2.amazonaws.com/assets/avatars/AvatarAssets/3D%20Assets/Hands/WizardStaff/WizardStaff.fbx"
]